### PR TITLE
fix(security): raise the transitive security floors in the typescript SDK examples

### PR DESCRIPTION
**Pull request by langwatch-agent**
Re-homes #6449 onto the post-restructure paths. The five example apps under `sdks/typescript/examples/` keep their own standalone npm lockfiles, so the workspace-wide pnpm overrides in `pnpm-workspace.yaml` never reach them and their transitive dependencies drifted behind. Each example already had an `overrides` block; this extends it and regenerates the lockfile.

## What it closes

**45 of the 50 open alerts** on these manifests: 19 HIGH, 25 MODERATE, 1 LOW.

| example | alerts closed | packages raised |
|---|---|---|
| `mastra` | 22 | `@hono/node-server` 1.19.14 to 2.1.0, `hono` 4.12.25 to 4.13.1, `ip-address` 10.2.0 to 10.5.0, `fast-uri` 4.0.0 to 4.1.2, `shell-quote` 1.8.4 to 1.10.0, `brace-expansion` 1.1.15/2.1.1 to 1.1.18/2.1.4, `js-yaml` 3.15.0 to 3.15.1, `@opentelemetry/core` 2.7.1+2.8.0 to 2.10.0, `protobufjs` 8.6.3 to 8.7.2 |
| `langgraph` | 8 | `js-yaml` 4.2.0 to 4.3.1, `linkify-it` 5.0.1 to 5.0.2, `uuid` 9.0.1+10.0.0 to 11.1.1, `@opentelemetry/core` and `propagator-jaeger` 2.7.1 to 2.10.0, `protobufjs` 8.6.3 to 8.7.2 |
| `langchain` | 7 | same set as langgraph, minus uuid |
| `vercel-ai` | 5 | `linkify-it`, `@opentelemetry/core`, `propagator-jaeger`, `protobufjs` |
| `evaluation` | 3 | `@opentelemetry/core`, `propagator-jaeger`, `protobufjs` |

Closure was computed by interval-testing each resolved version against the advisory's `vulnerableVersionRange`, not against `firstPatchedVersion`, so parallel major lines are not miscounted.

## What stays open, and why

Five alerts have no published fix, so no override can close them:

- `image-size` #2092, #2093 (HIGH). The advisory range is `<= 2.0.2` and 2.0.2 is the newest version on npm. Reached transitively through `mastra`.
- `@ai-sdk/provider-utils` #1963, #1981, #2003 (LOW). The advisory range is `<= 3.0.97`; the 3.x line tops out at 3.0.32. The 4.x subtree in `mastra` is already out of range.

These need either an upstream release or a dismissal decision. Nothing to do in this repo today.

## Scoped selectors where majors run in parallel

A blanket floor would have dragged already-patched majors backwards, so two entries are selector-scoped:

- `"uuid@<11.1.1": ">=11.1.1 <12"` in `langgraph`, replacing a bare `"uuid"` override. This lifts 9.0.1 and 10.0.0 and leaves the 14.0.0 subtree untouched.
- `"brace-expansion@<1.1.18"` and `"brace-expansion@>=2.0.0 <2.1.4"` in `mastra`, kept as separate 1.x and 2.x entries.

`@opentelemetry/core` is floored bluntly at `>=2.8.0 <3` here, which is safe in these five trees specifically: none of them carries a 1.x otel subtree, unlike the platform workspace.

## Version-set audit

Every lockfile was diffed as a set of resolved versions before and after:

```
evaluation   4 up, 0 down, 1 added (zod hoist), 0 removed
langchain    6 up, 0 down, 0 added, 0 removed
langgraph    6 up, 0 down, 0 added, 0 removed
vercel-ai    5 up, 0 down, 0 added, 0 removed
mastra       9 up, 0 down, 0 added, 0 removed
```

No downgrades and no dropped packages anywhere. The `langwatch` entry moving 0.33.1 to 1.4.0 in four of them is the local `file:../../` SDK picking up its current version.

## What was tested

No CI workflow builds these examples, so local verification is the only signal and it was done per example.

- `npm ci` from the regenerated lockfile in all five. All exit 0, which also proves each lockfile is consistent with its `package.json`.
- **`mastra` full build and boot**, since it takes the only major bump (`@hono/node-server` 1.x to 2.x). `npm run build` succeeds, then `node .mastra/output/index.mjs` serves: `GET /api/agents` returns 200 with the agent JSON, and `GET /api/logs` returns a correctly validated 400. Routing, middleware and the validator layer all work on `@hono/node-server` 2.1.0 with `hono` 4.13.1.
- Functional smoke of every raised package in the example that carries it, not just an import: `js-yaml` parses a document, `linkify-it` matches a URL, `uuid.v4()` returns a well-formed id, `JaegerPropagator().fields()` returns `["uber-trace-id"]`, `Address4.startAddress()` computes, `fast-uri.parse()` extracts a host, `shell-quote.parse()` tokenises, and a `Hono` app answers a routed request with 200.
- `@opentelemetry/core` 2.10.0, `@opentelemetry/sdk-node` 0.217.0 and `protobufjs` 8.7.2 load in every example that declares them.

## Two pre-existing problems this PR does not introduce

Both reproduce with main's own `package.json`, verified by reverting the file and re-running:

1. `langgraph` and `vercel-ai` cannot resolve without `--legacy-peer-deps`. In `vercel-ai`, `@vercel/otel` 1.14.1 peers `@opentelemetry/instrumentation >=0.46.0 <0.200.0` while the root pulls `sdk-node` 0.217.0. In `langgraph`, `@langchain/community` 1.1.29 wants `@langchain/core` 1.x while the root pins `^0.3.80`. Their lockfiles were regenerated with `--legacy-peer-deps`, which is how the checked-in versions were evidently produced.
2. `langchain`'s `npm run build` fails with `TS2688: Cannot find type definition file for 'node'` and the same for `'yauzl'`. Identical output and exit code on main with this branch's changes fully reverted. The example declares `typescript` but no `@types/node`.

Worth fixing, but both are separate from a dependency floor bump and neither should hold this up.

Supersedes #6449, which targeted the pre-restructure `typescript-sdk/examples/*` paths and has been unrebaseable since those paths moved.

## Summary by CodeRabbit

- **Chores**
  - Updated dependency version constraints across TypeScript examples to improve compatibility and consistency.
  - Refined package version ranges for telemetry, protobuf, YAML, linking, networking, and related tooling.
  - Raised the minimum supported `protobufjs` version in applicable examples.

### CODE REVIEW

File: sdks/typescript/examples/langgraph/package.json [hunk 1]
```diff
@@ -28,9 +28,14 @@
     "dotenv-cli": "^10.0.0"
   },
   "overrides": {
+    "@grpc/grpc-js": ">=1.14.4",
+    "@opentelemetry/core": ">=2.8.0 <3",
+    "@opentelemetry/propagator-jaeger": ">=2.9.0 <3",
     "axios": "^1.15.0",
```
[the remark this answers is not in the document]
Comment (langwatch-agent) [reply sdks/typescript/examples/langgraph/package.json]: Good catch, fixed in a897c9a.

Set to `>=1.16.0 <2` rather than `>=1.16.0`, so the floor cannot float across a future major on its own.

Two notes for anyone reading this later:

The floor was genuinely weaker than policy, but it is currently inert: nothing in this example resolves axios at all, so the regenerated `package-lock.json` is byte-identical and no alert closes. What it removes is a latent trap, since the moment any dependency starts pulling axios the old `^1.15.0` would have pinned it inside the vulnerable 1.15.x line.

The reason the root policy did not already cover it is the thing this PR is about: `sdks/typescript/examples/*` each carry a standalone npm lockfile outside the pnpm workspace, so the `overrides` block in `pnpm-workspace.yaml` never reaches them. I swept the other four examples for the same shape and this was the only caret-form override across all five.

`npm ci` still exits 0 and closure holds at 45 of 50.
