### PR TITLE
fix(ci): build mcp-server before app install in all CI workflows

### LINKED ISSUE #2995: fix(ci): e2e-ci fails on every PR — @langwatch/mcp-server dist/ not built before app startup
## Problem

The `sdk-javascript-ci / e2e` and `e2e-ci` jobs fail on both PRs and main with:

```
Error: Cannot find module '/home/runner/work/langwatch/langwatch/langwatch/node_modules/@langwatch/mcp-server/dist/create-mcp-server.js'
```

The app server (`langwatch/src/server.ts`) imports from `@langwatch/mcp-server`, but CI workflows don't build the MCP server package before starting the app. The `dist/` directory doesn't exist at runtime.

After this crash, the app never comes up on port 5570 and e2e global-setup times out after 30 fetch retries.

## Evidence

- Failing on main: https://github.com/langwatch/langwatch/actions/runs/24191651059
- Same failure on PR branches — not caused by any PR changes
- Two `e2e-ci` workflow runs trigger on every PR push (duplicate workflow files); one passes, the other fails

## Root causes

1. **Missing build step** — `@langwatch/mcp-server` is a workspace package whose `dist/` must be built before `pnpm start:app`. Neither `sdk-javascript-ci.yml` nor `e2e-ci` workflows build it.
2. **Duplicate e2e-ci workflows** — two workflow files match, causing duplicate runs that race on the same build artifacts.

## Fix

- Add a build step for `mcp-server` before app startup in CI:
  ```yaml
  - name: Build MCP server
    run: cd mcp-server && pnpm build
  ```
- Identify and remove the duplicate `e2e-ci` workflow definition
- Optionally: add a sanity check that verifies workspace dist dirs exist before starting the app

## Impact

Blocks PRs from going fully green even when the code is correct. Requires maintainer intuition to distinguish real failures from this infra issue.

### PR DESCRIPTION
**Pull request by drewdrewthis**
## Why

Closes #2995
Closes #3049

The mcp-server package is a workspace dependency of langwatch. When CI runs pnpm install for the app, it expects mcp-server/dist/ to already exist. Without a prior build step, pnpm install fails or produces broken installs.

Additionally, e2e tests were failing because the app re-ran migrations during pnpm start, which raced with the test setup.

## What changed

- Added Build mcp-server step before app install in: e2e-ci.yml, langwatch-app-ci.yml, langwatch-server-publish.yml, sdk-javascript-ci.yml
- Added mcp-server/pnpm-lock.yaml to pnpm cache keys
- Added SKIP_PRISMA_MIGRATE, SKIP_ELASTIC_MIGRATE, SKIP_CLICKHOUSE_MIGRATE env vars to e2e test run step

## Test plan

- CI passes on all 4 affected workflows
- e2e tests no longer fail with Cannot find module mcp-server/dist
- e2e tests no longer race on migrations during app startup

### CODE REVIEW

**Review by drewdrewthis — COMMENTED** [review]
Non-blocking hygiene note: `langwatch-server-publish.yml` uses `pnpm install` for the mcp-server build while the other three workflows (`e2e-ci.yml`, `langwatch-app-ci.yml`, `sdk-javascript-ci.yml`) use `pnpm install --frozen-lockfile`. For a publish workflow, reproducible installs are especially important — consider `--frozen-lockfile` for consistency and to prevent silent lockfile drift in published artifacts.

**Comment by drewdrewthis** [comment]
@drewdrewthis good catch — applied `--frozen-lockfile` to the mcp-server build in `langwatch-server-publish.yml` in 19554464d to match the other three workflows.

**Review by 0xdeafcafe — APPROVED** [review]
